=== sachinkrishna233/CAT2/student.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="College">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedInt">
                                        <xs:minInclusive value="1"></xs:minInclusive>
                                        <xs:maxInclusive value="8"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stu-name" type="xs:string" />
                            <xs:element name="Stu-Course" type="xs:string" />
                            <xs:element name="Stu-Sem">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedShort">
                                        <xs:minInclusive value="1"></xs:minInclusive>
                                        <xs:maxInclusive value="8"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stu-Sub1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedInt">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stu-Sub2">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedInt">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stu-Sub3">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedInt">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stu-Total">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedInt">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="300"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stu-Avg">
                                <xs:simpleType>
                                    <xs:restriction base="xs:float">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sachinkrishna233/CAT2/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="student.xsl" type="text/xsl"?>
<College xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">
    <Student>
        <id>1</id>
        <Stu-name>Abhi</Stu-name>
        <Stu-Course>MDS</Stu-Course>
        <Stu-Sem>1</Stu-Sem>
        <Stu-Sub1>77</Stu-Sub1>
        <Stu-Sub2>86</Stu-Sub2>
        <Stu-Sub3>75</Stu-Sub3>
        <Stu-Total>238</Stu-Total>
        <Stu-Avg>79.33</Stu-Avg>
    </Student>
    <Student>
        <id>2</id>
        <Stu-name>Rohan</Stu-name>
        <Stu-Course>MCA</Stu-Course>
        <Stu-Sem>2</Stu-Sem>
        <Stu-Sub1>77</Stu-Sub1>
        <Stu-Sub2>86</Stu-Sub2>
        <Stu-Sub3>75</Stu-Sub3>
        <Stu-Total>238</Stu-Total>
        <Stu-Avg>95</Stu-Avg>
    </Student>
</College>
